### ISSUE TITLE
Commenting your code

### ISSUE THREAD

**Issue by luisortizuriarte** [jwill96/Assignment-3#1]
Your code would benefit from comments detailing what you are doing. For example, you do some processing of your index data, but it's not super clear what you're aiming for there. Also, what is your index?

**Comment by jwill96** [comment]
The index that I used is the Central Indian Precipitation (core monsoon region) which was in the link of indexes you provided from NOAA. I wanted to find the years when the Central Indian Precipitation anomalies were positive, negative, and neutral. Then, I wanted to select data from the Global Precipitation Climatology Project (GPCP) Monthly Precipitation Data and select the years that matched with positive, negative, and neutral anomalies that I found from the index. I added some comments to the code to make it easier to follow what I am doing.

**Comment by luisortizuriarte** [comment]
Great! All issues now closed.
