### ISSUE TITLE
Too thin colorbar

### ISSUE THREAD

**Issue by luisortizuriarte** [jwill96/Assignment-3#2]
Your composite differences 2-panel and 3-panel plots has a colorbar that is way too thin to be legible. Since you are specifying the colorbar height in the line:

`cbar_ax = fig.add_axes([0.25, 0.18, 0.5, 0.012])`

you should be able to make it thicker by changing the last value (0.012) to something larger.

**Comment by jwill96** [comment]
I made the colorbars thicker by changing the last value to 0.025 or greater depending on how much space I had.

**Comment by luisortizuriarte** [comment]
Great!
